modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "GNU GPL 3.0"

[[mods]]
modId = "tradeloot"
version = "${version}"
displayName = "tradeloot"
logoFile = "icon.png"
authors = ""
description = '''

'''

[[dependencies.tradeloot]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tradeloot]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tradeloot]]
modId = "architectury"
mandatory = true
versionRange = "[6.6.92,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.tradeloot]]
modId = "cloth_config"
mandatory = true
versionRange = "[8,)"
ordering = "NONE"
side = "CLIENT"

