modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "GNU GPL 3.0"

[[mods]]
modId = "tradeloot"
version = "${version}"
displayName = "tradeloot"
logoFile = "icon.png"
authors = ""
description = '''

'''

[[dependencies.tradeloot]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tradeloot]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tradeloot]]
modId = "architectury"
mandatory = true
versionRange = "[4.0.29,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.tradeloot]]
modId = "cloth_config"
mandatory = true
versionRange = "[6,)"
ordering = "NONE"
side = "CLIENT"

