modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "GNU GPL 3.0"

[[mods]]
modId = "tradeloot"
version = "${version}"
displayName = "tradeloot"
logoFile = "icon.png"
authors = "Bfybf"
description = "Allow villagers to drop their trade items"

[[dependencies.tradeloot]]
modId = "neoforge"
type = "required"
versionRange = "[20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tradeloot]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tradeloot]]
modId = "architectury"
type = "required"
versionRange = "[12.1.4,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.tradeloot]]
modId = "cloth_config"
mandatory = true
versionRange = "[14,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "tradeloot.mixins.json"